### ISSUE TITLE
Error initializing detector ... no such file or directory

### ISSUE THREAD

**Issue by brunoqc** [nvcook42/morgoth#14] opened 2015-01-29 15:12 UTC
I didn't use vagrant (since I already have grafana and influxdb) but I ran the commands from [bootstrap.sh](https://github.com/nvcook42/morgoth/blob/c71374c5a48c808f6eb3b398f31e7a2472939575/bootstrap.sh).

My config looks like this (just to be sure mydatabase is a database in influxdb and myserie is a influxdb serie that I can query with `SELECT * FROM myserie` :

```yaml
---
engine:
  influxdb:
    host: localhost
    port: 8086
    user: myuser
    password: mypass
    database: mydatabase

schedule:
  rotations:
    - {period: 2m, resolution: 2s}
    - {period: 4m, resolution: 4s}
    - {period: 8m, resolution: 8s}
    - {period: 24m, resolution: 24s}
  delay: 15s

metrics:
  - pattern: myserie.*
    detectors:
      - mgof:
          min: 0
          max: 800
    notifiers:
      - riemann: {}

fittings:
  - rest:
      port: 7000
  - graphite: {}

logging:
    level: INFO
```

```
bbigras@ubuntunew:/gopath/src/github.com/nvcook42/morgoth$ ./run
E0129 10:06:16.327578   19947 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.a387fa3b36b07261e8f60802fea21053e6054621: no such file or directory
E0129 10:06:16.331366   19947 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.df602f5168cb9bb029364667726bfbd3d2d6cc17: no such file or directory
E0129 10:06:16.333158   19947 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.b89270bafd8b2c741930d51d04bb9359dbf97f26: no such file or directory
E0129 10:06:16.334486   19947 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.d82d32f5923504dd11b831c17cb851a81fcd2c83: no such file or directory
E0129 10:06:16.338714   19947 config.go:73] Error getting configured notifier: dial tcp 127.0.0.1:5555: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x81006f5]

goroutine 20 [running]:
github.com/nvcook42/morgoth/metric.(*ManagerStruct).NewMetric(0x18776b10, 0x18792140, 0x35)
        /gopath/src/github.com/nvcook42/morgoth/metric/manager.go:52 +0x165
github.com/nvcook42/morgoth/app.(*writerProxy).Insert(0x187770e0, 0xcc5c4362, 0xe, 0x0, 0x8540c80, 0x18792140, 0x35, 0x0, 0x0)
        /gopath/src/github.com/nvcook42/morgoth/app/writer_proxy.go:18 +0x4f
github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).handleConnection(0x187869c0, 0xb75c9638, 0x1871c7a0)
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:70 +0x726
created by github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).Start
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:39 +0x2fc

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0x187869e0)
        /usr/local/go/src/sync/waitgroup.go:132 +0x13e
github.com/nvcook42/morgoth/app.(*App).Run(0x18779b00, 0x0, 0x0)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:114 +0xb2b
main.main()
        /gopath/src/github.com/nvcook42/morgoth/morgoth.go:24 +0x155

goroutine 5 [chan receive]:
goroutine 7 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 8 [chan receive]:
github.com/nvcook42/morgoth/app.(*App).signalHandler(0x18779b00)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:137 +0xe8
created by github.com/nvcook42/morgoth/app.(*App).Run
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:72 +0x124

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0x18735678, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18735678, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).accept(0x18735640, 0x0, 0xb75c7ec8, 0x187771a8)
        /usr/local/go/src/net/fd_unix.go:419 +0x34f
net.(*TCPListener).AcceptTCP(0x1871c790, 0x18754480, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x1871c790, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x48
net/http.(*Server).Serve(0x18735780, 0xb75caa80, 0x1871c790, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x7b
net/http.Serve(0xb75caa80, 0x1871c790, 0xb75caaa0, 0x1872cfdc, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1606 +0x8c
github.com/nvcook42/morgoth/fitting/rest.(*RESTFitting).Start(0x1872cfc0, 0xb75c9498, 0x18779b00)
        /gopath/src/github.com/nvcook42/morgoth/fitting/rest/rest.go:48 +0x772
github.com/nvcook42/morgoth/app.func·001(0xb75ca908, 0x1872cfc0, 0x187869e0)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:104 +0x12f
created by github.com/nvcook42/morgoth/app.(*App).Run
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:105 +0x8ee

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0x187352f8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x187352f8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).Read(0x187352c0, 0x18788000, 0x1000, 0x1000, 0x0, 0xb75c7ec8, 0x18776efc)
        /usr/local/go/src/net/fd_unix.go:242 +0x2f0
net.(*conn).Read(0x1871c578, 0x18788000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xba
net/http.noteEOFReader.Read(0xb75ca700, 0x1871c578, 0x1872cbcc, 0x18788000, 0x1000, 0x1000, 0x18735180, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x5c
net/http.(*noteEOFReader).Read(0x18776bf0, 0x18788000, 0x1000, 0x1000, 0x18786060, 0x0, 0x0)
        <autogenerated>:125 +0x9f
bufio.(*Reader).fill(0x18732c90)
        /usr/local/go/src/bufio/bufio.go:97 +0x15c
bufio.(*Reader).Peek(0x18732c90, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xd2
net/http.(*persistConn).readLoop(0x1872cba0)
        /usr/local/go/src/net/http/transport.go:842 +0x87
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xa45

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0x1872cba0)
        /usr/local/go/src/net/http/transport.go:945 +0x31a
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xa5a

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0x187356f8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x187356f8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).accept(0x187356c0, 0x0, 0xb75c7ec8, 0x187771e8)
        /usr/local/go/src/net/fd_unix.go:419 +0x34f
net.(*TCPListener).AcceptTCP(0x1871c798, 0x18718ee8, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x1871c798, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x48
github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).Start(0x187869c0, 0xb75c9498, 0x18779b00)
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:35 +0x2b2
github.com/nvcook42/morgoth/app.func·001(0xb75ca928, 0x187869c0, 0x187869e0)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:104 +0x12f
created by github.com/nvcook42/morgoth/app.(*App).Run
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:105 +0x8ee

goroutine 15 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0xf08eb000, 0x1b, 0x77359400, 0x0, 0xcc5c43d0, 0xe, 0x0, 0x855cbe0, 0xf08eb000, 0x1b)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325

goroutine 16 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0xe11d6000, 0x37, 0xee6b2800, 0x0, 0xcc5c43d0, 0xe, 0x0, 0x855cbe0, 0xe11d6000, 0x37)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325

goroutine 18 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0xc23ac000, 0x6f, 0xdcd65000, 0x1, 0xcc5c44c0, 0xe, 0x0, 0x855cbe0, 0xc23ac000, 0x6f)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325

goroutine 19 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0x46b04000, 0x14f, 0x9682f000, 0x5, 0xcc5c44c0, 0xe, 0x0, 0x855cbe0, 0x46b04000, 0x14f)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325
exit status 2
godep: go exit status 1
```

**Comment by nvcook42** [comment] 2015-01-29 16:12
A quick hack is the delete this directory:
/gopath/src/github.com/nvcook42/morgoth/meta/


What is happening is the detectors store state in this directory in the form of a key value database. The key value database being used sometimes gets corrupt. ( I am still looking into the cause). For now just blow away the dir and things should start working again.

**Comment by brunoqc** [comment] 2015-01-29 16:42
If I delete the meta directory I get :
```
bbigras@ubuntunew:/gopath/src/github.com/nvcook42/morgoth$ rm -rf /gopath/src/github.com/nvcook42/morgoth/meta
bbigras@ubuntunew:/gopath/src/github.com/nvcook42/morgoth$ ./run
E0129 11:32:20.545826   21358 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.a387fa3b36b07261e8f60802fea21053e6054621: no such file or directory
E0129 11:32:20.549229   21358 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.df602f5168cb9bb029364667726bfbd3d2d6cc17: no such file or directory
E0129 11:32:20.550184   21358 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.b89270bafd8b2c741930d51d04bb9359dbf97f26: no such file or directory
E0129 11:32:20.551213   21358 config.go:58] Error initializing detector open /gopath/src/github.com/nvcook42/morgoth/meta/.d82d32f5923504dd11b831c17cb851a81fcd2c83: no such file or directory
```

It's fine if I was an empty meta directory.

Now I have a panic because `supervisor` is null at https://github.com/nvcook42/morgoth/blob/c71374c5a48c808f6eb3b398f31e7a2472939575/metric/manager.go#L52

I didn't get a warning from the `glog.Warningf` line but if I add a `fmt.Println` line, `id` is `windowsServers.<hostname>.system.processorqueuelength`. The hostname should not be used by that influxdb database, I don't know where it comes from. The string's format makes me wonder if I was using this with graphite.

```
bbigras@ubuntunew:/gopath/src/github.com/nvcook42/morgoth$ ./run
E0129 11:29:55.389667   18514 config.go:73] Error getting configured notifier: dial tcp 127.0.0.1:5555: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x81006f5]

goroutine 10 [running]:
github.com/nvcook42/morgoth/metric.(*ManagerStruct).NewMetric(0x1870a530, 0x18792000, 0x35)
        /gopath/src/github.com/nvcook42/morgoth/metric/manager.go:52 +0x165
github.com/nvcook42/morgoth/app.(*writerProxy).Insert(0x1870ad80, 0xcc5c56fe, 0xe, 0x0, 0x8540c80, 0x18792000, 0x35, 0x0, 0x0)
        /gopath/src/github.com/nvcook42/morgoth/app/writer_proxy.go:18 +0x4f
github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).handleConnection(0x18786720, 0xb74f96f8, 0x187de078)
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:70 +0x726
created by github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).Start
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:39 +0x2fc

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0x18786740)
        /usr/local/go/src/sync/waitgroup.go:132 +0x13e
github.com/nvcook42/morgoth/app.(*App).Run(0x18779ac0, 0x0, 0x0)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:114 +0xb2b
main.main()
        /gopath/src/github.com/nvcook42/morgoth/morgoth.go:24 +0x155

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x855cce0)
        /gopath/src/github.com/golang/glog/glog.go:879 +0x76
created by github.com/golang/glog.init·1
        /gopath/src/github.com/golang/glog/glog.go:410 +0x1ff

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1

goroutine 7 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 8 [chan receive]:
github.com/nvcook42/morgoth/app.(*App).signalHandler(0x18779ac0)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:137 +0xe8
created by github.com/nvcook42/morgoth/app.(*App).Run
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:72 +0x124

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0x18778838, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18778838, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).accept(0x18778800, 0x0, 0xb74f7ec8, 0x1870ad50)
        /usr/local/go/src/net/fd_unix.go:419 +0x34f
net.(*TCPListener).AcceptTCP(0x1871c6a0, 0x18757680, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x1871c6a0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x48
net/http.(*Server).Serve(0x187788c0, 0xb74fabd0, 0x1871c6a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x7b
net/http.Serve(0xb74fabd0, 0x1871c6a0, 0xb74fabf0, 0x187e061c, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1606 +0x8c
github.com/nvcook42/morgoth/fitting/rest.(*RESTFitting).Start(0x187e0600, 0xb74f93f8, 0x18779ac0)
        /gopath/src/github.com/nvcook42/morgoth/fitting/rest/rest.go:48 +0x772
github.com/nvcook42/morgoth/app.func·001(0xb74faa58, 0x187e0600, 0x18786740)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:104 +0x12f
created by github.com/nvcook42/morgoth/app.(*App).Run
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:105 +0x8ee

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0x18778478, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18778478, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).Read(0x18778440, 0x1887c000, 0x1000, 0x1000, 0x0, 0xb74f7ec8, 0x1870ab54)
        /usr/local/go/src/net/fd_unix.go:242 +0x2f0
net.(*conn).Read(0x1871c4c0, 0x1887c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xba
net/http.noteEOFReader.Read(0xb74fa850, 0x1871c4c0, 0x1872e14c, 0x1887c000, 0x1000, 0x1000, 0x1872c600, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x5c
net/http.(*noteEOFReader).Read(0x1870a5a0, 0x1887c000, 0x1000, 0x1000, 0x18738620, 0x0, 0x0)
        <autogenerated>:125 +0x9f
bufio.(*Reader).fill(0x187324e0)
        /usr/local/go/src/bufio/bufio.go:97 +0x15c
bufio.(*Reader).Peek(0x187324e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xd2
net/http.(*persistConn).readLoop(0x1872e120)
        /usr/local/go/src/net/http/transport.go:842 +0x87
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xa45

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0x1872e120)
        /usr/local/go/src/net/http/transport.go:945 +0x31a
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xa5a

goroutine 22 [IO wait]:
net.(*pollDesc).Wait(0x18778938, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18778938, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).accept(0x18778900, 0x0, 0xb74f7ec8, 0x187e20d4)
        /usr/local/go/src/net/fd_unix.go:419 +0x34f
net.(*TCPListener).AcceptTCP(0x1871c6b0, 0x187196e8, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x1871c6b0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x48
github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).Start(0x18786720, 0xb74f93f8, 0x18779ac0)
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:35 +0x2b2
github.com/nvcook42/morgoth/app.func·001(0xb74faa78, 0x18786720, 0x18786740)
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:104 +0x12f
created by github.com/nvcook42/morgoth/app.(*App).Run
        /gopath/src/github.com/nvcook42/morgoth/app/app.go:105 +0x8ee

goroutine 23 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0xf08eb000, 0x1b, 0x77359400, 0x0, 0xcc5c5708, 0xe, 0x0, 0x855cbe0, 0xf08eb000, 0x1b)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325

goroutine 24 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0xe11d6000, 0x37, 0xee6b2800, 0x0, 0xcc5c5780, 0xe, 0x0, 0x855cbe0, 0xe11d6000, 0x37)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325

goroutine 25 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0xc23ac000, 0x6f, 0xdcd65000, 0x1, 0xcc5c5780, 0xe, 0x0, 0x855cbe0, 0xc23ac000, 0x6f)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325

goroutine 26 [sleep]:
github.com/nvcook42/morgoth/schedule.func·001(0x46b04000, 0x14f, 0x9682f000, 0x5, 0xcc5c5b40, 0xe, 0x0, 0x855cbe0, 0x46b04000, 0x14f)
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:50 +0x3c3
created by github.com/nvcook42/morgoth/schedule.(*Schedule).Start
        /gopath/src/github.com/nvcook42/morgoth/schedule/schedule.go:58 +0x325
exit status 2
godep: go exit status 1
```

**Comment by nvcook42** [comment] 2015-01-29 17:43
Are you using riemann? If not then remove the riemann line from the notifiers config section. 

Riemann runs on port 5555. Looks like startup is crashing trying to talk to riemann.
Error getting configured notifier: dial tcp 127.0.0.1:5555: connection refused

**Comment by brunoqc** [comment] 2015-01-29 18:17
> Are you using riemann?

No. Sorry about that. That got rid of the `dial tcp` error.

The crash is caused by the `invalid memory address or nil pointer dereference`.

Now I still have :

```
bbigras@ubuntunew:/gopath/src/github.com/nvcook42/morgoth$ ./run                                                                                                                           [102/2201]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x81006f5]

goroutine 21 [running]:
github.com/nvcook42/morgoth/metric.(*ManagerStruct).NewMetric(0x18783190, 0x18710190, 0x35)
        /gopath/src/github.com/nvcook42/morgoth/metric/manager.go:52 +0x165
github.com/nvcook42/morgoth/app.(*writerProxy).Insert(0x187836c0, 0xcc5c6f3b, 0xe, 0x0, 0x8540c80, 0x18710190, 0x35, 0x0, 0x0)
        /gopath/src/github.com/nvcook42/morgoth/app/writer_proxy.go:18 +0x4f
github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).handleConnection(0x187eaae0, 0xb75486d0, 0x187dc078)
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:70 +0x726
created by github.com/nvcook42/morgoth/fitting/graphite.(*GraphiteFitting).Start
        /gopath/src/github.com/nvcook42/morgoth/fitting/graphite/graphite.go:39 +0x2fc
```

**Comment by brunoqc** [comment] 2015-01-29 20:25
It's weird that I don't have the crash on Windows with the same config file.

**Comment by brunoqc** [comment] 2015-01-30 14:26
If I understand correctly, morgoth is accessed using a REST api.

I'm able to get data with :
http://localhost:7000/data/myserie?start=5&stop=999999999999

I don't get data with the anomalies request (I'm not sure if I just need to wait or if the [return nil](https://github.com/nvcook42/morgoth/blob/12a3183ec09e3a36e7259642d2c5e7f0ece723c6/engine/influxdb/engine.go#L158) means it's not implemented yet.  :
http://localhost:7000/anomalies/myserie?start=5&stop=999999999999

**Comment by nvcook42** [comment] 2015-01-30 18:16
You are correct there is a simple REST api. The anomalies endpoint is not implemented yet.

https://github.com/nvcook42/morgoth/blob/c71374c5a48c808f6eb3b398f31e7a2472939575/engine/influxdb/engine.go#L157

Pull requests are welcome.

**Comment by nvcook42** [comment] 2015-01-30 22:40
I just pushed a fix to for the original issue with the panic.

**Closed** 2015-01-31 15:28 UTC

**Comment by nvcook42** [comment] 2015-02-03 03:23
I have implemented the /anomalies endpoint. It doesn't honor start and stop parameters as you might expect but it works for now.
